services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@angular-workshop-cluste.d1dldux.mongodb.net/?appName=Angular-workshop-cluster
      - JWT_SECRET=${JWT_SECRET}
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:80"